steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/y-junctions/pipeline:latest
      - -t
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/y-junctions/pipeline:$BUILD_ID
      - -f
      - pipeline/Dockerfile
      - .

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/y-junctions/pipeline:latest
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/y-junctions/pipeline:$BUILD_ID

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
